apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuxtalk-deployment
  labels:
    app: tuxtalk
spec:
  replicas: 1  # 원하는 복제본 수를 설정
  selector:
    matchLabels:
      app: tuxtalk
  template:
    metadata:
      labels:
        app: tuxtalk
    spec:
      containers:
        - name: tuxtalk-container
          image: mskim6518/argocd-k8s-v2:tuxtalk-0.0.1-4  # 사용할 Docker 이미지
          ports:
            - containerPort: 8080  # 애플리케이션이 사용하는 포트
---
apiVersion: v1
kind: Service
metadata:
  name: tuxtalk-service
  labels:
    app: tuxtalk
spec:
  type: NodePort  # 외부에서 접근할 서비스
  ports:
    - port: 80  # 외부에서 접근하는 포트
      targetPort: 8080  # 컨테이너 내부에서 서비스되는 포트
      nodePort: 30080
  selector:
    app: tuxtalk
